/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/aobox-transformed.glb --types --output src/Aobox-transformed.tsx 
*/

import * as THREE from 'three'
import React, { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

// FIX 1: Removed the 'animations' property
export type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  // FIX 2: Cast to 'unknown' first for safer type assertion
  const { nodes, materials } = useGLTF('/aobox-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/aobox-transformed.glb')